receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'your-api-metrics'
          scrape_interval: 60s
          metrics_path: '/actuator/prometheus'
          scheme: 'http'
          static_configs:
            - targets: ['host.docker.internal:8081']

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlphttp:
    endpoint: "http://host.docker.internal:8080"
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging, otlphttp, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
